# Generated by Django 5.2.7 on 2025-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Формат: +7XXXXXXXXXX', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
