# Generated by Django 5.2.7 on 2026-04-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0004_city_warehouse_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='orders.salon', verbose_name='Салон'),
        ),
    ]
