# Generated by Django 5.2.7 on 2026-10-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_measurement_signatures'),
        ('users', '0005_user_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_salons',
            field=models.ManyToManyField(blank=True, related_name='group_leaders', to='orders.salon', verbose_name='Салоны руководителя группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('service_manager', 'Сервис-менеджер'), ('manager', 'Менеджер'), ('installer', 'Монтажник'), ('complaint_department', 'Отдел рекламаций'), ('admin', 'Администратор'), ('leader', 'Руководитель подразделения'), ('group_leader', 'Руководитель группы салонов')], default='service_manager', max_length=50),
        ),
    ]
