# Generated by Django 5.2.7 on 2025-10-23 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='added_to_shipping_registry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Добавлено в реестр на отгрузку'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='client_agreement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования с клиентом'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('manager', 'Менеджер'), ('installer', 'Монтажник'), ('factory', 'Фабрика')], max_length=20, null=True, verbose_name='Тип рекламации'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='factory_response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа фабрики'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='installer_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'installer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный монтажник'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_shipped',
            field=models.BooleanField(default=False, verbose_name='Отгружено'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='planned_installation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланированная дата монтажа'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='planned_shipping_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланированная дата отгрузки'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='production_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок готовности производства'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('in_production', 'Заказ в производстве'), ('on_warehouse', 'Товар на складе'), ('shipping_overdue', 'Отгрузка просрочена'), ('factory_dispute', 'Спор с фабрикой'), ('factory_response_overdue', 'Ответ фабрики просрочен'), ('sm_response_overdue', 'СМ просрочил ответ'), ('under_sm_review', 'На проверке у СМ'), ('waiting_installer_date', 'Ожидает дату от монтажника'), ('needs_planning', 'Нужно запланировать'), ('installer_not_planned', 'Монтажник не запланировал'), ('shipping_planned', 'Отгрузка запланирована'), ('installation_planned', 'Монтаж запланирован'), ('both_planned', 'Отгрузка и монтаж запланированы'), ('resolved', 'Решена'), ('closed', 'Закрыта'), ('rejected', 'Отклонена'), ('sent', 'Отправлена')], default='new', max_length=30, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('push', 'Push-уведомление'), ('sms', 'SMS'), ('email', 'Email'), ('pc', 'Уведомление на ПК')], max_length=10, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.complaint', verbose_name='Рекламация')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
