# Generated by Django 5.2.7 on 2025-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_complaint_added_to_shipping_registry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='commercial_offer_text',
            field=models.TextField(blank=True, verbose_name='Описание коммерческого предложения'),
        ),
    ]
