# Generated by Django 5.2.7 on 2025-10-24 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_complaint_commercial_offer_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в реестр')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('doors_count', models.PositiveIntegerField(default=1, verbose_name='Количество дверей')),
                ('lift_type', models.CharField(choices=[('our', 'Наш'), ('client', 'Клиент')], max_length=10, verbose_name='Чей подъем')),
                ('lift_method', models.CharField(choices=[('elevator', 'Лифт'), ('manual', 'Ручной')], max_length=10, verbose_name='Как подъем')),
                ('order_type', models.CharField(choices=[('main', 'Основной'), ('complaint', 'Рекламация')], default='main', max_length=10, verbose_name='Вид заказа')),
                ('payment_status', models.CharField(blank=True, max_length=100, verbose_name='Оплата')),
                ('delivery_destination', models.CharField(choices=[('client', 'Клиент'), ('warehouse', 'На склад')], default='client', max_length=10, verbose_name='Куда везем')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('delivery_status', models.CharField(choices=[('pending', 'Ожидает отгрузки'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус доставки')),
                ('client_rating', models.PositiveSmallIntegerField(blank=True, help_text='От 1 до 5', null=True, verbose_name='Оценка клиента (доставка)')),
                ('planned_shipping_date', models.DateTimeField(blank=True, null=True, verbose_name='Запланированная дата отгрузки')),
                ('actual_shipping_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата отгрузки')),
                ('complaint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_entry', to='projects.complaint', verbose_name='Рекламация')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Запись в реестре отгрузки',
                'verbose_name_plural': 'Реестр на отгрузку',
                'ordering': ['-created_at'],
            },
        ),
    ]
