# Generated by Django 5.2.7 on 2025-10-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_shippingregistry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='is_shipped',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='shipped_at',
        ),
    ]
