# Generated by Django 5.2.7 on 2025-11-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_complaint_is_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintattachment',
            name='attachment_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ'), ('commercial_offer', 'Коммерческое предложение')], max_length=20, verbose_name='Тип вложения'),
        ),
    ]
