# Generated by Django 5.2.7 on 2025-11-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_complaintattachment_attachment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='problem_description',
        ),
    ]
