# Generated by Django 5.2.7 on 2025-11-05 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_complaint_problem_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='projects_no_recipie_1ca138_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['complaint', '-created_at'], name='projects_no_complai_f5ba73_idx'),
        ),
    ]
