# Generated by Django 5.2.7 on 2025-11-05 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_notification_is_read_notification_read_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер заказа'),
        ),
    ]
