# Generated by Django 5.2.7 on 2025-11-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_complaint_manager'),
    ]

    operations = [
    ]
