# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def assign_default_manager(apps, schema_editor):
    """Назначаем менеджера для существующих рекламаций без менеджера"""
    Complaint = apps.get_model('projects', 'Complaint')
    User = apps.get_model('users', 'User')
    
    # Получаем первого доступного менеджера
    default_manager = User.objects.filter(role='manager').first()
    
    if default_manager:
        # Обновляем все рекламации без менеджера
        complaints_without_manager = Complaint.objects.filter(manager__isnull=True)
        complaints_without_manager.update(manager=default_manager)
        print(f"Назначен менеджер {default_manager.username} для {complaints_without_manager.count()} рекламаций")


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_complaint_status'),
    ]

    operations = [
        # Шаг 1: Назначаем менеджера для существующих записей
        migrations.RunPython(assign_default_manager, migrations.RunPython.noop),
        
        # Шаг 2: Делаем поле обязательным
        migrations.AlterField(
            model_name='complaint',
            name='manager',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='managed_complaints',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Менеджер заказа',
                limit_choices_to={'role': 'manager'}
            ),
        ),
    ]

