# Generated by Django 5.2.7 on 2025-11-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_make_manager_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('in_production', 'Заказ в производстве'), ('on_warehouse', 'Товар на складе'), ('shipping_overdue', 'Отгрузка просрочена'), ('factory_dispute', 'Спор с фабрикой'), ('factory_response_overdue', 'Ответ фабрики просрочен'), ('factory_approved', 'Ответ получен'), ('factory_rejected', 'Отказ'), ('sm_response_overdue', 'СМ просрочил ответ'), ('under_sm_review', 'На проверке у СМ'), ('waiting_installer_date', 'Ожидает дату от монтажника'), ('needs_planning', 'Нужно запланировать'), ('installer_not_planned', 'Монтажник не запланировал'), ('shipping_planned', 'Отгрузка запланирована'), ('installation_planned', 'Монтаж запланирован'), ('both_planned', 'Отгрузка и монтаж запланированы'), ('resolved', 'Решена'), ('closed', 'Закрыта'), ('rejected', 'Отклонена'), ('sent', 'Отправлена')], default='new', max_length=30, verbose_name='Статус'),
        ),
    ]
