# Generated by Django 5.2.7 on 2025-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_complaint_additional_info_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assignee_comment',
            field=models.TextField(blank=True, help_text='Необязательное пояснение для менеджера или монтажника', verbose_name='Комментарий менеджеру/монтажнику'),
        ),
    ]
