# Generated by Django 5.2.7 on 2026-01-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_complaint_installer_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='factory_approve_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий при одобрении фабрикой'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер изделия'),
        ),
    ]
