# Generated by Django 5.2.7 on 2026-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_complaint_sm_response_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectiveproduct',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование бракованного изделия'),
        ),
    ]
