# Generated by Django 5.2.7 on 2026-06-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_defectiveproduct_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectiveproduct',
            name='problem_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='defectiveproduct',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Наименование бракованного изделия'),
        ),
    ]
