# Generated by Django 5.2.7 on 2026-07-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_production_deadline_and_more'),
        ('projects', '0020_alter_defectiveproduct_problem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='source_order',
            field=models.ForeignKey(blank=True, help_text='Заказ, из которого создана рекламация (Фаза 6)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='orders.order', verbose_name='Заказ-источник'),
        ),
    ]
