# Generated by Django 5.2.7 on 2026-07-20 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_complaint_source_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='return_planned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланированная дата отгрузки возврата'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='return_product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование товара на возврат'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата запроса возврата'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='return_required',
            field=models.BooleanField(default=False, verbose_name='Требуется возврат товара'),
        ),
        migrations.CreateModel(
            name='ReturnRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в реестр')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('return_status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено на фабрику'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус возврата')),
                ('planned_return_date', models.DateTimeField(blank=True, null=True, verbose_name='Запланированная дата отгрузки возврата')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата отгрузки возврата')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_entry', to='projects.complaint', verbose_name='Рекламация')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Запись в реестре возврата',
                'verbose_name_plural': 'Реестр на возврат',
                'ordering': ['-created_at'],
            },
        ),
    ]
