# Generated by Django 5.2.7 on 2026-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_complaint_return_planned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='moscow_service_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания сервисной заявки Москва'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='moscow_service_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок решения по сервисной заявке Москва'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('in_production', 'Заказ в производстве'), ('on_warehouse', 'Товар на складе'), ('shipping_overdue', 'Отгрузка просрочена'), ('factory_dispute', 'Спор с фабрикой'), ('factory_response_overdue', 'Ответ фабрики просрочен'), ('factory_approved', 'Ответ получен'), ('factory_rejected', 'Отказ'), ('sm_response_overdue', 'СМ просрочил ответ'), ('under_sm_review', 'На проверке у СМ'), ('moscow_service', 'Сервисная заявка Москва'), ('moscow_service_overdue', 'Просрочка сервиса Москва'), ('waiting_installer_date', 'Ожидает дату от монтажника'), ('needs_planning', 'Нужно запланировать'), ('installer_not_planned', 'Монтажник не запланировал'), ('installer_overdue', 'Просрочена монтажником'), ('shipping_planned', 'Отгрузка запланирована'), ('installation_planned', 'Монтаж запланирован'), ('both_planned', 'Отгрузка и монтаж запланированы'), ('resolved', 'Решена'), ('closed', 'Закрыта'), ('rejected', 'Отклонена'), ('sent', 'Отправлена')], default='new', max_length=30, verbose_name='Статус'),
        ),
    ]
