# Generated by Django 5.2.7 on 2026-09-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoorSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Серия дверей',
                'verbose_name_plural': 'Серии дверей',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('norm_name', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Нормализованное название')),
                ('aliases', models.TextField(blank=True, help_text='По одному в строке. Как это название пишут в КП, если отличается.', verbose_name='Синонимы')),
            ],
            options={
                'verbose_name': 'Цвет двери',
                'verbose_name_plural': 'Цвета дверей',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='catalog_doorcolor_unique_name')],
            },
        ),
        migrations.CreateModel(
            name='DoorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('norm_name', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Нормализованное название')),
                ('aliases', models.TextField(blank=True, help_text='По одному в строке. Как это название пишут в КП, если отличается.', verbose_name='Синонимы')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.doorseries', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Модель двери',
                'verbose_name_plural': 'Модели дверей',
                'ordering': ['series__position', 'series__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, db_index=True, help_text='Номер или артикул полотна из каталога: 1, 12, AC36, Torino TR 702…', max_length=100, verbose_name='Вариант полотна')),
                ('image', models.ImageField(upload_to='catalog/doors/', verbose_name='Картинка')),
                ('source', models.CharField(choices=[('catalog', 'Из каталога'), ('manual', 'Загружена менеджером')], default='catalog', max_length=20, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.doorcolor', verbose_name='Цвет')),
                ('door_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.doormodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Картинка двери',
                'verbose_name_plural': 'Картинки дверей',
                'ordering': ['door_model', 'color', 'variant'],
                'constraints': [models.UniqueConstraint(fields=('door_model', 'color', 'variant'), name='catalog_doorimage_unique_variant')],
            },
        ),
        migrations.AddConstraint(
            model_name='doormodel',
            constraint=models.UniqueConstraint(fields=('series', 'name'), name='catalog_doormodel_unique_in_series'),
        ),
    ]
