# Generated by Django 5.2.7 on 2026-04-30 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_city_warehouse_notification_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('kp_number', models.CharField(blank=True, max_length=100, verbose_name='Номер КП')),
                ('kp_date', models.DateField(blank=True, null=True, verbose_name='Дата КП')),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон контакта')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('lift_available', models.BooleanField(blank=True, null=True, verbose_name='Есть лифт')),
                ('stairs_available', models.BooleanField(blank=True, null=True, verbose_name='Есть лестница')),
                ('floor_readiness', models.TextField(blank=True, verbose_name='Готовность пола')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('cancelled', 'Отменён')], default='draft', max_length=30, verbose_name='Статус')),
                ('commercial_offer', models.FileField(blank=True, null=True, upload_to='orders/commercial_offers/', verbose_name='Коммерческое предложение')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_number', models.PositiveSmallIntegerField(verbose_name='Номер проёма')),
                ('room_name', models.CharField(blank=True, max_length=255, verbose_name='Помещение')),
                ('model_name', models.CharField(blank=True, max_length=500, verbose_name='Модель')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('door_type', models.CharField(blank=True, choices=[('entrance', 'Входная'), ('interior', 'Межкомнатная'), ('other', 'Другое')], max_length=30, verbose_name='Тип двери')),
                ('opening_type', models.CharField(blank=True, choices=[('left', 'Левое'), ('right', 'Правое'), ('left_inner', 'Левое внутреннее'), ('right_inner', 'Правое внутреннее'), ('sliding', 'Раздвижное'), ('other', 'Другое')], max_length=30, verbose_name='Тип открывания')),
                ('door_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота полотна, мм')),
                ('door_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина полотна, мм')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ['position', 'opening_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/attachments/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order', verbose_name='Заказ')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.orderitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Вложение заказа',
                'verbose_name_plural': 'Вложения заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('box', 'Короб'), ('platband', 'Наличник'), ('extension', 'Добор'), ('hinges', 'Петли'), ('handle', 'Ручки'), ('mechanism', 'Механизм'), ('glass', 'Стекло'), ('extra', 'Доп. к заказу'), ('service', 'Услуга')], max_length=30, verbose_name='Вид')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('comment_face', models.TextField(blank=True, verbose_name='Комментарий лицо')),
                ('comment_back', models.TextField(blank=True, verbose_name='Комментарий торец')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.orderitem', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Дополнение к позиции',
                'verbose_name_plural': 'Дополнения к позициям',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salons', to='users.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.salon', verbose_name='Салон'),
        ),
    ]
