# Generated by Django 5.2.7 on 2026-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней активности'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_activity_kind',
            field=models.CharField(blank=True, choices=[('created', 'Заказ создан'), ('updated', 'Заказ обновлён'), ('items_changed', 'Изменены позиции'), ('status_changed', 'Изменён статус'), ('file_attached', 'Загружен файл'), ('comment_added', 'Добавлен комментарий'), ('measurement_requested', 'Заявка на замер'), ('measurement_scheduled', 'Замер запланирован'), ('measurement_done', 'Замер выполнен'), ('measurement_processed', 'Замер обработан')], default='', max_length=40, verbose_name='Вид активности'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='opening_type',
            field=models.CharField(blank=True, choices=[('A', 'A — правое наружнее, лицо снаружи'), ('B', 'B — правое наружнее, лицо внутри'), ('B_INVERSO', 'B Inverso — правое внутреннее, лицо снаружи'), ('C', 'C — левое наружнее, лицо снаружи'), ('D', 'D — левое наружнее, лицо внутри'), ('D_INVERSO', 'D Inverso — левое внутреннее, лицо снаружи')], max_length=30, verbose_name='Тип открывания'),
        ),
    ]
