# Generated by Django 5.2.7 on 2026-05-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_last_activity_at_order_last_activity_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('measurement_requested', 'Заявка на замер'), ('cancelled', 'Отменён')], default='draft', max_length=30, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='MeasurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Контактное лицо ФИО')),
                ('contact_position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Телефон контактного лица')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата замера')),
                ('payer', models.CharField(choices=[('client', 'Клиент'), ('salon', 'Салон')], default='client', max_length=20, verbose_name='Кто оплачивает замер')),
                ('opening_plan', models.FileField(blank=True, null=True, upload_to='orders/opening_plans/', verbose_name='План открывания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_measurement_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_request', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заявка на замер',
                'verbose_name_plural': 'Заявки на замер',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderActionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(verbose_name='Срок')),
                ('action_text', models.CharField(max_length=500, verbose_name='Действие')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('notified', models.BooleanField(default=False, help_text='True после отправки in-app уведомления при наступлении due_at', verbose_name='Уведомление отправлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_action_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_reminders', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Наработка',
                'verbose_name_plural': 'Наработки',
                'ordering': ['done', 'due_at'],
                'indexes': [models.Index(fields=['done', 'due_at'], name='orders_orde_done_448c8b_idx'), models.Index(fields=['order', 'done'], name='orders_orde_order_i_aa9853_idx')],
            },
        ),
    ]
