# Generated by Django 5.2.7 on 2026-05-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_measurementrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('box', 'Короб'), ('platband', 'Наличник'), ('extension', 'Добор'), ('hinges', 'Петли'), ('handle', 'Ручки'), ('mechanism', 'Механизм'), ('glass', 'Стекло'), ('extra', 'Доп. к заказу'), ('service', 'Услуга')], max_length=30, verbose_name='Вид')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Поддерживаются дробные значения (наличников может быть 1.5)', max_digits=10, verbose_name='Количество')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('opening_type', models.CharField(blank=True, choices=[('A', 'A — правое наружнее, лицо снаружи'), ('B', 'B — правое наружнее, лицо внутри'), ('B_INVERSO', 'B Inverso — правое внутреннее, лицо снаружи'), ('C', 'C — левое наружнее, лицо снаружи'), ('D', 'D — левое наружнее, лицо внутри'), ('D_INVERSO', 'D Inverso — левое внутреннее, лицо снаружи')], max_length=30, verbose_name='Открывание (для коробов)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Сопутствующая позиция',
                'verbose_name_plural': 'Сопутствующие позиции',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='OrderItemAddon',
        ),
    ]
