# Generated by Django 5.2.7 on 2026-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderaddon_delete_orderitemaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recommended_opening_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рекомендуемая высота проёма, мм'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='recommended_opening_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рекомендуемая ширина проёма, мм'),
        ),
    ]
