# Generated by Django 5.2.7 on 2026-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_recommended_opening_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('measurement_requested', 'Заявка на замер'), ('paid', 'Оплачен'), ('in_production', 'В производстве'), ('on_warehouse', 'На складе'), ('shipped', 'Отгружен'), ('completed', 'Выполнен'), ('cancelled', 'Не актуален')], default='draft', max_length=30, verbose_name='Статус'),
        ),
    ]
