# Generated by Django 5.2.7 on 2026-05-15 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Создан'), ('measurement_requested', 'Заявка на замер'), ('measurement_scheduled', 'Замер запланирован'), ('measurement_done', 'Замер выполнен'), ('measurement_processed', 'Замер обработан'), ('paid', 'Оплачен'), ('in_production', 'В производстве'), ('on_warehouse', 'На складе'), ('shipped', 'Отгружен'), ('completed', 'Выполнен'), ('cancelled', 'Не актуален')], default='draft', max_length=30, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время замера')),
                ('signature_photo', models.FileField(blank=True, null=True, upload_to='orders/signatures/', verbose_name='Фото подписанного бланка')),
                ('client_access_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Используется в публичной ссылке на PDF без авторизации', unique=True, verbose_name='Публичный токен для PDF')),
                ('is_done', models.BooleanField(default=False, verbose_name='Замер выполнен')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Замер обработан менеджером')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='orders.measurementrequest', verbose_name='Заявка на замер')),
                ('service_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to=settings.AUTH_USER_MODEL, verbose_name='Сервис-менеджер')),
            ],
            options={
                'verbose_name': 'Замер',
                'verbose_name_plural': 'Замеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_number', models.PositiveSmallIntegerField(verbose_name='Номер проёма')),
                ('room_name', models.CharField(blank=True, max_length=255, verbose_name='Помещение')),
                ('actual_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическая высота, мм')),
                ('actual_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическая ширина, мм')),
                ('actual_depth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическая глубина, мм')),
                ('door_height_by_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота двери по Заказу')),
                ('door_width_by_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина двери по Заказу')),
                ('recommended_door_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рек. высота двери')),
                ('recommended_door_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рек. ширина двери')),
                ('recommended_opening_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рек. высота проёма')),
                ('recommended_opening_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рек. ширина проёма')),
                ('change_target', models.CharField(blank=True, choices=[('door', 'Меняем дверь'), ('opening', 'Меняем проём'), ('both', 'Меняем дверь и проём')], max_length=20, verbose_name='Что меняем')),
                ('new_door_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новая высота двери')),
                ('new_door_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новая ширина двери')),
                ('opening_type', models.CharField(blank=True, choices=[('A', 'A — правое наружнее, лицо снаружи'), ('B', 'B — правое наружнее, лицо внутри'), ('B_INVERSO', 'B Inverso — правое внутреннее, лицо снаружи'), ('C', 'C — левое наружнее, лицо снаружи'), ('D', 'D — левое наружнее, лицо внутри'), ('D_INVERSO', 'D Inverso — левое внутреннее, лицо снаружи')], max_length=30, verbose_name='Открывание')),
                ('addon_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина добора, мм')),
                ('face_trim_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Наличник лицевой, кол-во')),
                ('face_trim_comment', models.TextField(blank=True, verbose_name='Комментарий лицевой')),
                ('back_trim_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Наличник оборотный, кол-во')),
                ('back_trim_comment', models.TextField(blank=True, verbose_name='Комментарий оборотный')),
                ('extra_hardware', models.TextField(blank=True, verbose_name='Доп. фурнитура')),
                ('threshold', models.TextField(blank=True, verbose_name='Порог')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания / рекомендации')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='orders.measurement', verbose_name='Замер')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_openings', to='orders.orderitem', verbose_name='Позиция заказа')),
            ],
            options={
                'verbose_name': 'Проём (замер)',
                'verbose_name_plural': 'Проёмы (замер)',
                'ordering': ['opening_number'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/measurements/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.measurement', verbose_name='Замер')),
                ('opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.measurementopening', verbose_name='Проём')),
            ],
            options={
                'verbose_name': 'Вложение замера',
                'verbose_name_plural': 'Вложения замера',
            },
        ),
    ]
