# Generated by Django 5.2.7 on 2026-06-27 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_measurement_opening_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='production_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата готовности'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата запуска в производство'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_activity_kind',
            field=models.CharField(blank=True, choices=[('created', 'Заказ создан'), ('updated', 'Заказ обновлён'), ('items_changed', 'Изменены позиции'), ('status_changed', 'Изменён статус'), ('file_attached', 'Загружен файл'), ('comment_added', 'Добавлен комментарий'), ('measurement_requested', 'Заявка на замер'), ('measurement_scheduled', 'Замер запланирован'), ('measurement_done', 'Замер выполнен'), ('measurement_processed', 'Замер обработан'), ('sms_sent', 'Отправлено SMS клиенту')], default='', max_length=40, verbose_name='Вид активности'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Создан'), ('measurement_requested', 'Заявка на замер'), ('measurement_scheduled', 'Замер запланирован'), ('measurement_done', 'Замер выполнен'), ('measurement_processed', 'Замер обработан'), ('paid', 'Оплачен'), ('in_production', 'В производстве'), ('on_warehouse', 'На складе'), ('shipped', 'Отгружен'), ('completed', 'Выполнен'), ('cancelled', 'Не актуален'), ('measurement_not_planned', 'Замер не запланирован'), ('measurement_not_done', 'Замер не выполнен'), ('measurement_not_processed', 'Замер не обработан')], default='draft', max_length=30, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OrderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Заказ создан'), ('updated', 'Заказ обновлён'), ('items_changed', 'Изменены позиции'), ('status_changed', 'Изменён статус'), ('file_attached', 'Загружен файл'), ('comment_added', 'Добавлен комментарий'), ('measurement_requested', 'Заявка на замер'), ('measurement_scheduled', 'Замер запланирован'), ('measurement_done', 'Замер выполнен'), ('measurement_processed', 'Замер обработан'), ('sms_sent', 'Отправлено SMS клиенту')], max_length=40, verbose_name='Вид события')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('old_status', models.CharField(blank=True, max_length=40, verbose_name='Старый статус')),
                ('new_status', models.CharField(blank=True, max_length=40, verbose_name='Новый статус')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('actor', models.ForeignKey(blank=True, help_text='Пусто = системное событие (cron)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие заказа',
                'verbose_name_plural': 'Журнал событий заказа',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_007d19_idx')],
            },
        ),
    ]
