# Generated by Django 5.2.7 on 2026-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_production_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='short_code',
            field=models.CharField(blank=True, editable=False, help_text='Короткая ссылка /z/{код} → PDF-бланк (для SMS клиенту)', max_length=12, null=True, unique=True, verbose_name='Короткий код для SMS-ссылки'),
        ),
    ]
