# Generated by Django 5.2.7 on 2026-07-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_backfill_measurement_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сохранён в черновиках'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='СМ сохранил замер в черновиках, чтобы проверить и отправить позже', verbose_name='Черновик'),
        ),
    ]
