# Generated by Django 5.2.7 on 2026-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_measurement_draft_saved_at_measurement_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carry_to_entrance',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужен пронос до подъезда'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Этаж'),
        ),
    ]
