# Generated by Django 5.2.7 on 2026-07-20 09:42

from django.db import migrations, models


def mark_manual_doors(apps, schema_editor):
    """
    Проёмы, где был задан «желаемый размер двери», переводим в ручной режим:
    рек. дверь уже равна желаемой (старый авторасчёт подставлял её), поэтому
    достаточно проставить флаг — размеры сохраняются.
    """
    MeasurementOpening = apps.get_model('orders', 'MeasurementOpening')
    MeasurementOpening.objects.exclude(
        desired_door_height__isnull=True, desired_door_width__isnull=True
    ).update(recommended_door_is_manual=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_carry_to_entrance_order_floor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementopening',
            name='recommended_door_is_manual',
            field=models.BooleanField(default=False, verbose_name='Рек. размер двери задан СМ вручную'),
        ),
        migrations.RunPython(mark_manual_doors, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='measurementopening',
            name='desired_door_height',
        ),
        migrations.RemoveField(
            model_name='measurementopening',
            name='desired_door_width',
        ),
    ]
