# Generated by Django 5.2.7 on 2026-08-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_measurementopening_desired_door_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementopening',
            name='recommended_door_width_parts',
            field=models.CharField(blank=True, max_length=50, verbose_name='Рек. ширина полотен (сумма)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='door_width_parts',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ширина полотен (сумма)'),
        ),
        migrations.AlterField(
            model_name='measurementopening',
            name='door_type',
            field=models.CharField(blank=True, choices=[('entrance', 'Входная'), ('interior', 'Межкомнатная'), ('sliding', 'Сдвижная'), ('double', 'Двустворчатая'), ('other', 'Другое')], max_length=30, verbose_name='Тип двери'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='door_type',
            field=models.CharField(blank=True, choices=[('entrance', 'Входная'), ('interior', 'Межкомнатная'), ('sliding', 'Сдвижная'), ('double', 'Двустворчатая'), ('other', 'Другое')], max_length=30, verbose_name='Тип двери'),
        ),
    ]
