# Generated by Django 5.2.7 on 2026-08-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_measurementopening_recommended_door_width_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='repeat_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Повторных замеров'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='repeat_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='Причина повторного замера'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='repeat_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Повторный замер назначен'),
        ),
        migrations.AddField(
            model_name='measurementopening',
            name='addon_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Добор, количество'),
        ),
        migrations.AlterField(
            model_name='measurementopening',
            name='addon_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина добора, мм (устар.)'),
        ),
    ]
