# Generated by Django 5.2.7 on 2026-08-26 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_measurement_repeat_count_measurement_repeat_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementRequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/opening_plans/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.measurementrequest', verbose_name='Заявка на замер')),
            ],
            options={
                'verbose_name': 'Файл заявки на замер',
                'verbose_name_plural': 'Файлы заявки на замер',
                'ordering': ['id'],
            },
        ),
    ]
