# Generated by Django 5.2.7 on 2026-09-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_measurementrequestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='glass_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость стекла'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость товара'),
        ),
        migrations.AddField(
            model_name='order',
            name='products_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость изделий'),
        ),
        migrations.AddField(
            model_name='order',
            name='services_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость услуг'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итого без скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итого со скидкой'),
        ),
    ]
