# Generated by Django 5.2.7 on 2026-09-07 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0019_order_discount_amount_order_glass_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTextPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('header_text', models.TextField(blank=True, help_text='Например: «Искусственное покрытие EVO / современное решение для мебели и интерьеров»', verbose_name='Заголовок слайда')),
                ('included_text', models.TextField(blank=True, help_text='По одному пункту в строке.', verbose_name='В стоимость комплекта входит')),
                ('features_text', models.TextField(blank=True, help_text='По одному пункту в строке.', verbose_name='Преимущества')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Текстовый блок КП',
                'verbose_name_plural': 'Текстовые блоки КП',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrettyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Выводится внизу, под всеми проёмами.', verbose_name='Комментарий к КП')),
                ('goods_amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость товара и изделий (правка)')),
                ('services_amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость услуг (правка)')),
                ('total_amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итого без скидки (правка)')),
                ('total_with_discount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итого со скидкой (правка)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pretty_offers', to=settings.AUTH_USER_MODEL, verbose_name='Кто сформировал')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretty_offer', to='orders.order', verbose_name='Заказ')),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='orders.offertextpreset', verbose_name='Текстовый блок')),
            ],
            options={
                'verbose_name': 'Красивое КП',
                'verbose_name_plural': 'Красивые КП',
            },
        ),
        migrations.CreateModel(
            name='PrettyOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Выводится отдельным полем рядом с моделью.', verbose_name='Описание проёма')),
                ('two_sided', models.BooleanField(default=False, verbose_name='Двусторонняя дверь')),
                ('front_custom_image', models.ImageField(blank=True, upload_to='orders/pretty_offer/', verbose_name='Своя картинка (лицо)')),
                ('back_custom_image', models.ImageField(blank=True, upload_to='orders/pretty_offer/', verbose_name='Своя картинка (оборот)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('back_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.doorimage', verbose_name='Картинка (оборот)')),
                ('front_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.doorimage', verbose_name='Картинка (лицо)')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.prettyoffer', verbose_name='КП')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretty_offer_items', to='orders.orderitem', verbose_name='Позиция заказа')),
                ('preset', models.ForeignKey(blank=True, help_text='Пусто — берётся блок всего КП.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_items', to='orders.offertextpreset', verbose_name='Текстовый блок')),
            ],
            options={
                'verbose_name': 'Проём красивого КП',
                'verbose_name_plural': 'Проёмы красивого КП',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrettyOfferAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/pretty_offer/', verbose_name='Картинка')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.prettyoffer', verbose_name='КП')),
                ('offer_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.prettyofferitem', verbose_name='Проём')),
            ],
            options={
                'verbose_name': 'Картинка красивого КП',
                'verbose_name_plural': 'Картинки красивого КП',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='prettyofferitem',
            constraint=models.UniqueConstraint(fields=('offer', 'order_item'), name='orders_prettyofferitem_unique_order_item'),
        ),
    ]
