# Generated by Django 5.2.7 on 2026-09-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_seed_offer_text_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='updated_after_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дополнен после выполнения'),
        ),
    ]
