# Generated by Django 5.2.7 on 2026-09-07 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_measurement_updated_after_done_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='irrelevant_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Неактуальность подтверждена'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='irrelevant_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_irrelevant_measurements', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='irrelevant_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='Причина неактуальности'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='irrelevant_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Помечен неактуальным'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='irrelevant_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrelevant_measurement_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто пометил'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='is_irrelevant',
            field=models.BooleanField(default=False, help_text='Менеджер подтвердил неактуальность — замер уходит из работы.', verbose_name='Неактуален'),
        ),
    ]
