# Generated by Django 5.2.7 on 2026-09-15 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_irrelevance_to_request(apps, schema_editor):
    """
    Переносим признак неактуальности с замера на заявку.

    Отказаться от замера могут ещё до того, как СМ назначил дату и замер
    появился, поэтому хранить это на замере было неправильно. Уже проставленные
    пометки не теряем.
    """
    Measurement = apps.get_model('orders', 'Measurement')
    fields = (
        'is_irrelevant', 'irrelevant_requested_at', 'irrelevant_requested_by_id',
        'irrelevant_reason', 'irrelevant_confirmed_at', 'irrelevant_confirmed_by_id',
    )
    for m in Measurement.objects.exclude(
        is_irrelevant=False, irrelevant_requested_at__isnull=True,
    ).select_related('request'):
        request = m.request
        for field in fields:
            setattr(request, field, getattr(m, field))
        request.save(update_fields=list(fields))


def move_irrelevance_back(apps, schema_editor):
    """Обратный перенос — чтобы миграция откатывалась без потери данных."""
    MeasurementRequest = apps.get_model('orders', 'MeasurementRequest')
    fields = (
        'is_irrelevant', 'irrelevant_requested_at', 'irrelevant_requested_by_id',
        'irrelevant_reason', 'irrelevant_confirmed_at', 'irrelevant_confirmed_by_id',
    )
    for request in MeasurementRequest.objects.exclude(
        is_irrelevant=False, irrelevant_requested_at__isnull=True,
    ):
        m = getattr(request, 'measurement', None)
        if m is None:
            continue
        for field in fields:
            setattr(m, field, getattr(request, field))
        m.save(update_fields=list(fields))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_measurement_irrelevant_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementrequest',
            name='irrelevant_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Неактуальность подтверждена'),
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='irrelevant_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_irrelevant_measurements', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил'),
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='irrelevant_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='Причина неактуальности'),
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='irrelevant_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Помечена неактуальной'),
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='irrelevant_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrelevant_measurement_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто пометил'),
        ),
        migrations.AddField(
            model_name='measurementrequest',
            name='is_irrelevant',
            field=models.BooleanField(default=False, help_text='Менеджер подтвердил неактуальность — заявка уходит из работы.', verbose_name='Неактуальна'),
        ),
        migrations.RunPython(move_irrelevance_to_request, move_irrelevance_back),
        migrations.RemoveField(
            model_name='measurement',
            name='irrelevant_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='irrelevant_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='irrelevant_reason',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='irrelevant_requested_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='irrelevant_requested_by',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='is_irrelevant',
        ),
    ]
