# Generated by Django 5.2.7 on 2026-09-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_measurement_request_irrelevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='prettyofferitem',
            name='addons',
            field=models.ManyToManyField(blank=True, help_text='Сопутствующие позиции заказа, которые показать на слайде проёма.', related_name='pretty_offer_items', to='orders.orderaddon', verbose_name='Позиции комплектации'),
        ),
        migrations.AlterField(
            model_name='prettyofferitem',
            name='description',
            field=models.TextField(blank=True, help_text='Выводится отдельным полем рядом с моделью.', verbose_name='Комплектация и описание проёма'),
        ),
    ]
