# Generated by Django 5.2.7 on 2026-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_prettyofferitem_addons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertextpreset',
            name='header_text',
            field=models.TextField(blank=True, help_text='В красивое КП больше не выводится: шапку слайда убрали, место отдано колонкам. Поле оставлено, чтобы не терять тексты.', verbose_name='Заголовок слайда (не печатается)'),
        ),
    ]
