# Generated by Django 5.2.7 on 2026-09-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_offertextpreset_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertextpreset',
            name='features_text',
            field=models.TextField(blank=True, help_text='В красивое КП больше не выводится — по той же причине, что и состав комплекта.', verbose_name='Преимущества (не печатается)'),
        ),
        migrations.AlterField(
            model_name='offertextpreset',
            name='included_text',
            field=models.TextField(blank=True, help_text='В красивое КП больше не выводится: в блоке «Комплектация и описание» теперь только набранное менеджером и выбранные позиции заказа.', verbose_name='В стоимость комплекта входит (не печатается)'),
        ),
    ]
