# Generated by Django 5.2.7 on 2026-10-04 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_prettyofferitemaddon_alter_prettyofferitem_addons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_designer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Есть дизайнер'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_probability',
            field=models.CharField(blank=True, choices=[('high', 'Высокая'), ('medium', 'Средняя'), ('low', 'Низкая')], max_length=10, verbose_name='Вероятность оформления'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_month',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемый месяц оплаты'),
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Фамилия и имя')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('studio', models.CharField(blank=True, max_length=255, verbose_name='Студия')),
                ('bonus_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Бонус, %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_designers', to=settings.AUTH_USER_MODEL, verbose_name='Кто завёл')),
            ],
            options={
                'verbose_name': 'Дизайнер',
                'verbose_name_plural': 'Дизайнеры',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.designer', verbose_name='Дизайнер'),
        ),
    ]
