# Generated by Django 5.2.7 on 2026-10-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_designer_and_sales_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='designer_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Выплачено дизайнеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда выплачено дизайнеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил выплату'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_activity_kind',
            field=models.CharField(blank=True, choices=[('created', 'Заказ создан'), ('updated', 'Заказ обновлён'), ('items_changed', 'Изменены позиции'), ('status_changed', 'Изменён статус'), ('file_attached', 'Загружен файл'), ('comment_added', 'Добавлен комментарий'), ('measurement_requested', 'Заявка на замер'), ('measurement_scheduled', 'Замер запланирован'), ('measurement_done', 'Замер выполнен'), ('measurement_processed', 'Замер обработан'), ('sms_sent', 'Отправлено SMS клиенту'), ('designer_paid', 'Выплата дизайнеру')], default='', max_length=40, verbose_name='Вид активности'),
        ),
        migrations.AlterField(
            model_name='orderactivitylog',
            name='kind',
            field=models.CharField(choices=[('created', 'Заказ создан'), ('updated', 'Заказ обновлён'), ('items_changed', 'Изменены позиции'), ('status_changed', 'Изменён статус'), ('file_attached', 'Загружен файл'), ('comment_added', 'Добавлен комментарий'), ('measurement_requested', 'Заявка на замер'), ('measurement_scheduled', 'Замер запланирован'), ('measurement_done', 'Замер выполнен'), ('measurement_processed', 'Замер обработан'), ('sms_sent', 'Отправлено SMS клиенту'), ('designer_paid', 'Выплата дизайнеру')], max_length=40, verbose_name='Вид события'),
        ),
    ]
