# Generated by Django 5.2.7 on 2026-10-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_designer_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Расстояние, км'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='distance_payment',
            field=models.CharField(blank=True, choices=[('on_site', 'Оплата на месте'), ('invoice', 'Включить в счёт')], max_length=10, verbose_name='Оплата удалённости'),
        ),
    ]
