# Generated by Django 5.2.7 on 2026-10-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_measurement_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementopening',
            name='has_panels',
            field=models.BooleanField(default=False, verbose_name='Панели'),
        ),
        migrations.AddField(
            model_name='measurementopening',
            name='panels_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Панели, кол-во'),
        ),
    ]
