# Generated by Django 5.2.7 on 2026-10-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_opening_panels'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementopening',
            name='working_leaf',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Рабочая створка'),
        ),
        migrations.AlterField(
            model_name='measurementopening',
            name='opening_type',
            field=models.CharField(blank=True, choices=[('A', 'A — правое наружнее, лицо снаружи'), ('B', 'B — правое наружнее, лицо внутри'), ('B_INVERSO', 'B Inverso — правое внутреннее, лицо снаружи'), ('C', 'C — левое наружнее, лицо снаружи'), ('D', 'D — левое наружнее, лицо внутри'), ('D_INVERSO', 'D Inverso — левое внутреннее, лицо снаружи'), ('A_C', 'A+C'), ('B_D', 'B+D'), ('B_D_INVERSO', 'B+D Inverso')], max_length=30, verbose_name='Открывание'),
        ),
        migrations.AlterField(
            model_name='orderaddon',
            name='opening_type',
            field=models.CharField(blank=True, choices=[('A', 'A — правое наружнее, лицо снаружи'), ('B', 'B — правое наружнее, лицо внутри'), ('B_INVERSO', 'B Inverso — правое внутреннее, лицо снаружи'), ('C', 'C — левое наружнее, лицо снаружи'), ('D', 'D — левое наружнее, лицо внутри'), ('D_INVERSO', 'D Inverso — левое внутреннее, лицо снаружи'), ('A_C', 'A+C'), ('B_D', 'B+D'), ('B_D_INVERSO', 'B+D Inverso')], max_length=30, verbose_name='Открывание (для коробов)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='opening_type',
            field=models.CharField(blank=True, choices=[('A', 'A — правое наружнее, лицо снаружи'), ('B', 'B — правое наружнее, лицо внутри'), ('B_INVERSO', 'B Inverso — правое внутреннее, лицо снаружи'), ('C', 'C — левое наружнее, лицо снаружи'), ('D', 'D — левое наружнее, лицо внутри'), ('D_INVERSO', 'D Inverso — левое внутреннее, лицо снаружи'), ('A_C', 'A+C'), ('B_D', 'B+D'), ('B_D_INVERSO', 'B+D Inverso')], max_length=30, verbose_name='Тип открывания'),
        ),
    ]
