# Generated by Django 5.2.7 on 2026-10-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_designer_city(apps, schema_editor):
    """
    Город уже заведённым дизайнерам: по городу менеджера, который завёл карточку
    (его город или город его салона), иначе — по городу салона первого заказа
    с этим дизайнером. Не нашли — город остаётся пустым, его поправят в админке.
    """
    Designer = apps.get_model('orders', 'Designer')
    Order = apps.get_model('orders', 'Order')
    for d in Designer.objects.select_related('created_by', 'created_by__salon'):
        city_id = None
        u = d.created_by
        if u is not None:
            city_id = u.city_id or (u.salon.city_id if u.salon_id else None)
        if city_id is None:
            order = Order.objects.filter(designer_id=d.id).select_related('salon').order_by('id').first()
            if order is not None and order.salon_id:
                city_id = order.salon.city_id
        if city_id is not None:
            d.city_id = city_id
            d.save(update_fields=['city'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_double_door_opening'),
        ('users', '0005_user_salon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designers', to='users.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.RunPython(fill_designer_city, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='designer',
            constraint=models.UniqueConstraint(fields=('city', 'phone'), name='designer_phone_unique_in_city'),
        ),
    ]
