# Generated by Django 5.2.7 on 2026-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_designer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementopening',
            name='client_uid',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Метка создания'),
        ),
    ]
