# Generated by Django 5.2.7 on 2026-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_opening_client_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='paid_on_site',
            field=models.BooleanField(default=False, verbose_name='Замер оплачен на месте'),
        ),
    ]
