# Generated by Django 5.2.7 on 2026-10-07 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_single_signatures(apps, schema_editor):
    """Одиночное фото подписи → первая запись списка. Файл не копируем, ссылаемся на тот же.
    Старое поле не чистим: откат миграции ничего не теряет."""
    Measurement = apps.get_model('orders', 'Measurement')
    MeasurementSignature = apps.get_model('orders', 'MeasurementSignature')
    for m in Measurement.objects.exclude(signature_photo='').exclude(signature_photo__isnull=True):
        sig = MeasurementSignature.objects.create(measurement=m, file=m.signature_photo.name)
        # Дата — когда замер последний раз меняли (точнее не знаем)
        MeasurementSignature.objects.filter(pk=sig.pk).update(created_at=m.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_measurement_paid_on_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/signatures/', verbose_name='Фото подписанного бланка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='orders.measurement', verbose_name='Замер')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Фото подписи замера',
                'verbose_name_plural': 'Фото подписей замера',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(copy_single_signatures, migrations.RunPython.noop),
    ]
